spring.application.name=csdmp

server.max-http-request-header-size=64KB

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/csdmp_db2}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:+012345678!}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=${JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY:votre_cle_tres_secrete_et_tres_longue_de_plus_de_32_caracteres}
security.jwt.expiration-time=${SECURITY_JWT_EXPIRATION_TIME:900000}
security.jwt.refresh-expiration-time=${SECURITY_JWT_REFRESH_EXPIRATION_TIME:604800000}